### PR TITLE
Update Icons.lua for API changes

### PR DESCRIPTION
**Pull request by geeet1**
Fix deprecated GetItemIcon function

### CODE REVIEW

**Comment by geeet1** [comment]
Although now that I tested it on retail, old function still works, on beta, it does not anymore.

**Comment by fang2hou** [comment]
Thanks, but WindTools just follow ElvUI's rule that it should be renamed to `local C_Item_GetItemIconByID = C_Item.GetItemIconByID`

**Comment by geeet1** [comment]
All good, this was just the fastest way to fix the error for me, instead of fixing every line that includes that old func. As long as it's not throwing errors anymore, I'm good with it.

**Comment by geeet1** [comment]
No idea what happened, I could swear I saw the file being fixed by you already, idk if I dreamed, anyways, there's the fix with the ElvUI's rule now.

**Pull request closed without merging**
